#ifndef VIEWCLASS_HPP
#define VIEWCLASS_HPP

enum class ViewClass
{
    MAIN_MENU,
    CHOOSE_CATEGORY,
    REVIEW_QUESTION,
    REVIEW_ANSWER,
    REVIEW_COMPLETE,
    DICT_MENU,
    DICT_INPUT,
    DICT_HISTORY,
    DICT_WORD,
    DICT_WORD_NOT_EXIST,
    EXAM_CHOOSE_NUMBER,
    EXAM_QUESTION,
    EXAM_ANSWER,
    EXAM_COMPLETE,
    TEXT_CHOOSE_FILE,
    TEXT_FILE_CHOSEN,
    TEXT_WORD,
    EDIT
};

#endif
